### ISSUE TITLE
PasswordVault missing on upgrade to pwsh 7.1.3

### ISSUE THREAD

**Issue by asherber** [MScholtes/CredentialLocker#1]
Running on Windows 10.0.19042. When I upgraded from pwsh 7.0.0 to 7.1.3 I started getting errors:

```
PS> show-vaultcredentials
New-Object: C:\Users\xxx\Documents\PowerShell\Modules\CredentialLocker\1.0.0\CredentialLocker.psm1:83
Line |
  83 |      $VAULT = New-Object Windows.Security.Credentials.PasswordVault
     |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find type [Windows.Security.Credentials.PasswordVault]: verify that the assembly containing this
     | type is loaded.

Show-VaultCredentials: Error retrieving credentials
```

**Comment by MScholtes** [comment]
Hello Aaron,

Microsoft is working on making _Powershell Core_ platfom independent beginning with _Powershell 7.1_. But instead of implementing APIs in _Linux_ that exist only in _Windows_ they delete _APIs_ completely without replacement. This happenend now to **_Windows.Security.Credentials.PasswordVault_** too! I see no way to work around this: the effort of adding an extra dll is too high for me.

Maybe you get it running with
```
Import-Module -Name CredentialLocker -UseWindowsPowerShell
```
(I have no example installation of _Powershell Core_)

Greetings and sorry

Markus

**Comment by asherber** [comment]
Thanks -- I wasn't expecting a breaking change like this between minor pwsh versions. 

FWIW, this will work if the CredentialLocker module is installed in Windows Powershell and then imported into Powershell Core as you suggest above.
